version: '3.8'

services:
  next-proxy:
    build: .
    container_name: next-proxy
    ports:
      - "2407:3000"  # Mapeia a porta 3000 do container para a porta 2407 do host
    environment:
      - NODE_ENV=production  # Defina o ambiente como produção, se necessário
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api  # URL do backend que pode ser acessado pela aplicação
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
